### ISSUE TITLE
Can I have some help?

### ISSUE THREAD

**Issue by Jckex** [DiscowZombie/UltimateTs#13]
I'm getting this: Im with FreeTS.ovh and I'm unaware of what to do, I've put the IP in the config and set the ids of the groups: Im getting this in console:

03.11 12:47:04 [Server] INFO Enabling UltimateTs v2.1.4
03.11 12:47:04 [Server] INFO (TeamSpeak) Bot Online!
03.11 12:47:05 [Server] INFO [SEVERE] TS3 command error: {msg=invalid loginname or password, id=520}
03.11 12:47:06 [Server] INFO [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=43}
03.11 12:47:07 [Server] INFO [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=43}
03.11 12:47:07 [Server] INFO [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=43}
03.11 12:47:07 [Server] INFO [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=43}
03.11 12:47:08 [Server] INFO [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=43}
03.11 12:47:08 [Server] INFO [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=43}
03.11 12:47:08 [Server] INFO [] ------------------------------ []
03.11 12:47:08 [Server] INFO UltimateTs | v2.1.4 | Author: DiscowZombie.
03.11 12:47:08 [Server] INFO Using 1.8.8-R0.1-SNAPSHOT | git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) | v1_8_R3.
03.11 12:47:08 [Server] INFO Your perms system is Vault.
03.11 12:47:08 [Server] INFO You can links ranks with Vault.
03.11 12:47:08 [Server] INFO Using FILE as storage type.
03.11 12:47:08 [Server] INFO [] ------------------------------ []

**Comment by DiscowZombie** [comment]
Hi,

You simply have entered a bad username or password.

**Comment by Jckex** [comment]
How do I find this information out?

**Comment by DiscowZombie** [comment]
If you are on a dedicated hosting (or a VPS), all informations (username + password) has been given the first time that you start your TeamSpeak (with the main privilege key). If you aren't with a dedicated machine (or a VPS), ask your hosting provider to get informations that you need.

**Comment by DiscowZombie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Isn](https://trello.com/c/WfbbOKwx/3-isn)
