### ISSUE TITLE
28.05 19:47:41 [Server] INFO [2017-05-28 19:47:41.454] [SEVERE] TS3 command error: {msg=invalid parameter size, id=1541}

### ISSUE THREAD

**Issue by Killdore** [DiscowZombie/UltimateTs#2]
`28.05 19:47:41 [Server] INFO [2017-05-28 19:47:41.454] [SEVERE] TS3 command error: {msg=invalid parameter size, id=1541}`

This is what I get when I connect MC and TS. Can I get some help?

**Comment by DiscowZombie** [comment]
Hi, 

I think this is why your config contain too many characters. The size of the messages is limited, have you changed this messages ?
`messages:
  poke: '[color=red]You need to register yourself before join TeamSpeak. Use ''/ts
    link'' IG to link your accounts.'
  kick: Please register yourself !`

_Eventual solutions:_ 
Try resetting the values of messages, like this:
`messages:
  poke: '[color=red]You need to register yourself before join TeamSpeak. Use ''/ts
    link'' IG to link your accounts.'
  kick: Please register yourself !`

Else, If they don't work with this two default messages, send me your config :)

**Comment by Killdore21** [comment]
Didn't work after I'd reset the two messages. But I don't use them anyeays, so its fine by me.

Here's my messages.yml:
`messages:
  poke: '[color=red]You need to register yourself before join TeamSpeak. Use ''/ts
    link'' IG to link your accounts.'
  kick: Please register yourself !
  bot:
    online: NordicBot koblet til TeamSpeak server!
    offline: NordicBot koblet fra TeamSpeak server!
  database:
    online: Koblet til databasen.
    offline: Koblet fra databasen.
  linked:
    sucess: '┃ NordicMc ┃ Du koblet sammen Minecraft med TeamSpeak! (Koblet til: %mcname%.
      &cFeil? Skriv /ts-koblefra og link på nytt.&b)'
    ready: '&8┃ &6NordicMc&8 ┃ &7Gå på TeamSpeak-serveren våres (&a/ts&7) for å koble
      til! (Eventuelt relogg TeamSpeak.)'
    desc: 'Minecraft Navn: %mcname%'
    already: '&8┃ &6NordicMc&8 ┃ &7Du har allerede koblet til Minecraft med TeamSpeak.
      (&cFeil? Skriv /ts-koblefra og link på nytt.&7)'
    linked: '&8┃ &6NordicMc&8 ┃ &7Du har allerede koblet til Minecraft med TeamSpeak.
      (&cFeil? Skriv /ts-koblefra og link på nytt.&b)'
    info: '&8┃ &6NordicMc&8 ┃ &7TeamSpeak-navnet ditt er: &a%tsname%.'
  unlinked:
    confirmation:
      confirmation: '&8┃ &6NordicMc&8 ┃ &c&lAdvarsel! &7Hvis du kobler fra Minecraft-brukeren
        din med TeamSpeak, vil alle TeamSpeak-gruppene du er med i bli fjernet fra
        deg. Er du sikker på at du vil gjære dette? Skriv ''YES'' eller ''NO'' i chatten.'
      'yes': '&8┃ &6NordicMc&8 ┃ &a&lSuksess! &7Du koblet fra Minecraft og TeamSpeak.'
      'no': '&8┃ &6NordicMc&8 ┃ &c&lKansellert! &bDu koblet ikke fra Minecraft og
        TeamSpeak.'
    already: '&8┃ &6NordicMc&8 ┃ &cDu har ikke koblet til Minecraft med TeamSpeak.'
    unlinked: '&8┃ &6NordicMc&8 ┃ &bDu har ikke koblet til Minecraft med TeamSpeak.'
  broadcast:
    empty: '&8┃ &6NordicMc&8 ┃ &cMeldingen kan ikke være tom.'
    to:
      teamspeak: '%message%'
      minecraft: '&8[&b&lTeamSpeak&8] &f%message%'
      sender: '&8┃ &6NordicMc&8 ┃ &aSuksess!'
  list:
    minecraft:
      size: '&8┃ &6NordicMc&8 ┃ &7Det er %n spillere pålogget:'
      player: '&8┃ &6NordicMc&8 ┃ &8- &f%player% &8- &7%uuid%'
      'false': '&8┃ &6NordicMc&8 ┃   &7Koblet til: &c%linked_true_false%'
      'true': '&8┃ &6NordicMc&8 ┃   &7Koblet til: &a%linked_true_false% &7med &b%linked_name%
        &8(&7%dbid%&8)'
    teamspeak:
      size: '&8┃ &6NordicMc&8 ┃ &2Det er %n spillere pålogget:'
      user: '&8┃ &6NordicMc&8 ┃ &8- &f%name% &8(&7%dbid%&8)'`

The æ/ø/å is from Norwegian, sorry about that.

**Comment by Killdore21** [comment]
1. messages:
2.   poke: '[color=red]You need to register yourself before join TeamSpeak. Use ''/ts
3.     link'' IG to link your accounts.'
4.   kick: Please register yourself !
5.   bot:
6.     online: NordicBot koblet til TeamSpeak server!
7.     offline: NordicBot koblet fra TeamSpeak server!
8.   database:
9.     online: Koblet til databasen.
10.     offline: Koblet fra databasen.
11.   linked:
12.     sucess: '┃ NordicMc ┃ Du koblet sammen Minecraft med TeamSpeak! (Koblet til: %mcname%.
13.       &cFeil? Skriv /ts-koblefra og link på nytt.&b)'
14.     ready: '&8┃ &6NordicMc&8 ┃ &7Gå på TeamSpeak-serveren våres (&a/ts&7) for å koble
15.       til! (Eventuelt relogg TeamSpeak.)'
16.     desc: 'Minecraft Navn: %mcname%'
17.     already: '&8┃ &6NordicMc&8 ┃ &7Du har allerede koblet til Minecraft med TeamSpeak.
18.       (&cFeil? Skriv /ts-koblefra og link på nytt.&7)'
19.     linked: '&8┃ &6NordicMc&8 ┃ &7Du har allerede koblet til Minecraft med TeamSpeak.
20.       (&cFeil? Skriv /ts-koblefra og link på nytt.&b)'
21.     info: '&8┃ &6NordicMc&8 ┃ &7TeamSpeak-navnet ditt er: &a%tsname%.'
22.   unlinked:
23.     confirmation:
24.       confirmation: '&8┃ &6NordicMc&8 ┃ &c&lAdvarsel! &7Hvis du kobler fra Minecraft-brukeren
25.         din med TeamSpeak, vil alle TeamSpeak-gruppene du er med i bli fjernet fra
26.         deg. Er du sikker på at du vil gjære dette? Skriv ''YES'' eller ''NO'' i chatten.'
27.       'yes': '&8┃ &6NordicMc&8 ┃ &a&lSuksess! &7Du koblet fra Minecraft og TeamSpeak.'
28.       'no': '&8┃ &6NordicMc&8 ┃ &c&lKansellert! &bDu koblet ikke fra Minecraft og
29.         TeamSpeak.'
30.     already: '&8┃ &6NordicMc&8 ┃ &cDu har ikke koblet til Minecraft med TeamSpeak.'
31.     unlinked: '&8┃ &6NordicMc&8 ┃ &bDu har ikke koblet til Minecraft med TeamSpeak.'
32.   broadcast:
33.     empty: '&8┃ &6NordicMc&8 ┃ &cMeldingen kan ikke være tom.'
34.     to:
35.       teamspeak: '%message%'
36.       minecraft: '&8[&b&lTeamSpeak&8] &f%message%'
37.       sender: '&8┃ &6NordicMc&8 ┃ &aSuksess!'
38.   list:
39.     minecraft:
40.       size: '&8┃ &6NordicMc&8 ┃ &7Det er %n spillere pålogget:'
41.       player: '&8┃ &6NordicMc&8 ┃ &8- &f%player% &8- &7%uuid%'
42.       'false': '&8┃ &6NordicMc&8 ┃   &7Koblet til: &c%linked_true_false%'
43.       'true': '&8┃ &6NordicMc&8 ┃   &7Koblet til: &a%linked_true_false% &7med &b%linked_name%
44.         &8(&7%dbid%&8)'
45.     teamspeak:
46.       size: '&8┃ &6NordicMc&8 ┃ &2Det er %n spillere pålogget:'
47.       user: '&8┃ &6NordicMc&8 ┃ &8- &f%name% &8(&7%dbid%&8)'

for lined support :P

**Comment by DiscowZombie** [comment]
Just a question, you get the error when you type /ts link or when you login to TeamSpeak?

**Comment by Killdore21** [comment]
Uhm, let me check

**Comment by Killdore21** [comment]
When I log on to TeamSpeak, then get linked.

**Comment by Killdore** [comment]
just to let you know, I've updated my GitHub-account ... Haven't used it in a while, logged in yesterday for this :P

**Comment by DiscowZombie** [comment]
Can you send me your folder UltimateTS/ who contain config.yml and messages.yml (you can modify config.yml to delete your IP and password) :) 

Thank

**Comment by Killdore** [comment]
https://hastebin.com/anumipoquk.bash

There. The ranks: does also have rank: because it didn't work for me, so I tried fix it.
And also, more ranks than srvadmin and test will come, but I tested it with those.

**Comment by Killdore** [comment]
Oh, files, sorry. Didn't see you edited your message...

[linkedPlayers.txt](https://github.com/DiscowZombie/UltimateTs/files/1036314/linkedPlayers.txt)
[messages.txt](https://github.com/DiscowZombie/UltimateTs/files/1036315/messages.txt)
[config.txt](https://github.com/DiscowZombie/UltimateTs/files/1036316/config.txt)

**Comment by DiscowZombie** [comment]
Hi !

I found your problem ! Your message here:
`  linked:
    sucess: '┃ NordicMc ┃ Du koblet sammen Minecraft med TeamSpeak! (Koblet til: %mcname%.
      &cFeil? Skriv /ts-koblefra og link på nytt.&b)'`
is too long (more than 200 characters). Unfortunately, you need to modify your message ;)

If your issues is fixed after this, close this :)
Don't forgot to post a reviews of this plugin If you like this,

Mathéo.

**Comment by Killdore** [comment]
Thanks, I got poked now!

But the ranks won't sync... Do you have to wait some time?

**Comment by DiscowZombie** [comment]
No, It's instant

**Comment by Killdore** [comment]
Well, it won't sync... Or wait, hold on.

**Comment by DiscowZombie** [comment]
What's perms system do you use ?

**Comment by Killdore** [comment]
PermissionsEX, on a database

**Comment by Killdore** [comment]
and I add ranks.(rank name in config) to myself, will it work for testing?

**Comment by DiscowZombie** [comment]
Your config is good but, I think it's because of you use PermEX on a Database, I will test this :)

**Comment by Killdore** [comment]
Ok, let me know.

**Comment by DiscowZombie** [comment]
After somes test, I found a new issues on he method `asignRank`, I will corrected this as soon as possible... Just wait a little :)

**Comment by Killdore** [comment]
Okay :)

**Comment by Killdore** [comment]
Do you think you'll get it fixed today? :)

**Comment by Killdore** [comment]
Uhm, I also use another plugin. The author said that I had problems, and not the plugin...
Going to *try* and make a plugin :P

**Comment by DiscowZombie** [comment]
Hi ! I think your problem where now fixed in 2.0.2. Try downloading: https://www.spigotmc.org/resources/ultimatets-link-minecraft-teamspeak-rank-easily-mysql-opensource.39076/download?version=162941

and use this config:
`login:
  ip: **HIDDEN**
  username: bot-sync
  password: **HIDDEN**
  port: 9987
bot:
  name: NordicBot
database:
  enable: false
  host: localhost
  name: databaseName
  user: root
  password: password
config:
  kickNotRegister: false
  defaultGroupId: 8
  assignWhenRegister: 9
perms:
  group:
    svradmin: 6
    test: 7
  rank:
    svradmin: 6
    test: 7`

_Sorry for the long time delay :(_

**Comment by Killdore** [comment]
Thanks for the new download.
It worked! :D

And the delay is okay. I didn't expect the bug get fixed in like, 4 days.

Thanks :)

**Comment by Killdore** [comment]
Can you add so you can cystomize YES or NO when you unlink it? So you can say YES or NO in your own language, if you translate it :P

**Comment by DiscowZombie** [comment]
Hi ! Next time open a new issue to suggested changes :) But Yes, I will add this ;)

If you like the plugin, don't forget to give a reviews on spigot: https://www.spigotmc.org/resources/ultimatets-link-minecraft-teamspeak-rank-easily-mysql-opensource.39076/.

Thank.
