### ISSUE TITLE
Issue-streak! When users are offline on TS, the /ts status won't work.

### ISSUE THREAD

**Issue by Killdore** [DiscowZombie/UltimateTs#4]
https://hastebin.com/yavozixori.vbs

https://gyazo.com/104064ac14811dda276fe88801ff2b96
(First line to ENG: "| NordicMC | You have linked Minecraft with TeamSpeak. Getting information ...")

**Comment by DiscowZombie** [comment]
Hi,

sorry for the delay _(massive exams :/)_ but your hastebin link do not work :/ Can you give me a new link ?

**Comment by Killdore** [comment]
Sure, hold on ...

**Comment by Killdore** [comment]
Seems like hastebin doesn't respond when I try hastebin.com. here is a pastebin-link: https://pastebin.com/CtAJJ0ZY

I used MyCommand to perform the command. (/ts shows the IP and the /ultimatets:ts status.)

**Comment by DiscowZombie** [comment]
Ok, I will work to fix this ! :P

**Comment by Killdore** [comment]
Thanks! :)

I'll go afk for some minutes, so sorry if I don't respond.
But I get email notifications, so I'll come back asap. :)

**Comment by DiscowZombie** [comment]
I released [v2.1.2](https://www.spigotmc.org/resources/ultimatets-link-minecraft-teamspeak-rank-easily-mysql-opensource.39076/update?update=170621) : Can you tried with this and removed your _/ts_ command on MyCommand ? :)

**Comment by Killdore** [comment]
That's not the main issue. On MyCommand, /ts shows the IP with raw text and also runs /ultimatets:ts status, to ofc. check what you've linked it to. The issue is that when a player is offline on TeamSpeak, the /ultimatets:ts status won't work. Just says An internal error occoured while performing this command.

**Comment by DiscowZombie** [comment]
> to ofc. check what you've linked it to. The issue is that when a player is offline on TeamSpeak, the /ultimatets:ts status won't work. Just says An internal error occoured while performing this command.

But, I do not get this issues ? Can you tried in v2.1.2 ? :)

**Comment by Killdore** [comment]
Can sure do. I may have said it wrong, let me try it.

It looked like the 'Join TeamSpeak: ts.spigotmc.org' was the main thing you've fixed in v2.1.2

**Comment by DiscowZombie** [comment]
> It looked like the 'Join TeamSpeak: ts.spigotmc.org' was the main thing you've fixed in v2.1.2

I fix littles others thinks _(But it does not show so I do not say)_

**Comment by Killdore** [comment]
Still says an error.

**Comment by DiscowZombie** [comment]
Strange, I'll do other checks ;)

**Comment by Killdore** [comment]
Thanks :)

**Comment by Killdore** [comment]
I think the best idea is to store the last name he/she had on the TeamSpeak server, in linkedPlayers.yml

**Comment by DiscowZombie** [comment]
Fixed in [v2.1.3](https://www.spigotmc.org/resources/ultimatets-link-minecraft-teamspeak-rank-easily-mysql-opensource.39076/update?update=170631) :)

**Comment by Killdore** [comment]
Okay. Will check it in a minute...
________________________________

**Comment by Killdore** [comment]
It worked! :)

**Comment by DiscowZombie** [comment]
perfect ! have fun with the plugin ! :D

**Comment by Killdore** [comment]
I always do <3
