### ISSUE TITLE
MySQL Table already exists

### ISSUE THREAD

**Issue by Walbern** [DiscowZombie/UltimateTs#5]
Howdy @DiscowZombie !

I get this message in my console:
https://hastebin.com/amalipiwax.md

I do not get any errors when I start the plugin the first time on my server, but whenever I restart the server and the plugin needs to connect to my SQL Db again, I get this error.

It states that I already have a table in my SQL db, which is true, but I do not wish to reset the tables in my SQL db everytime I restart the server. Could you possibly look into this and perhaps re-code this part of your plugin?

Best regards,

Walbern

**Comment by DiscowZombie** [comment]
Hi @Walbern,

sure enough, it seems to have a problem, I'll watch this :)

**Comment by Walbern** [comment]
Awesome, thank you!

**Comment by DiscowZombie** [comment]
Hi :)

Can you tried with this ? https://www.mediafire.com/?sa3sr9yb8ouvs5r

**Comment by Walbern** [comment]
Works! Fixed issue #5.
