### ISSUE TITLE
Channel Only Configuration

### ISSUE THREAD

**Issue by Artapel** [DiscowZombie/UltimateTs#8]
Hi Guys, Can i setup this plugin so that it only interacts with one channel on my teamspeak server?

**Comment by DiscowZombie** [comment]
Hi,

I think I don't correctly understand the question But You need to know that : "The bot only watch user when they join the default channel. If user do not join this channel, they get not her ranks and her accounts wasn't linked". 

If you think I did not understand your question, please rephrase it.
Thanks, DiscowZombie.

**Comment by DiscowZombie** [comment]
I close this issue, reason : More than 1 month without new reply.
